### PR TITLE
Repo structure

### PR DESCRIPTION
**Pull request by amykapernick**

### CODE REVIEW

**Review by mishmanners — APPROVED** [review]

**Comment by mishmanners** [comment]
Yay I fixed it! I'm learning a heap about these merge conflicts 💚

**Comment by mishmanners** [comment]
Not sure why the test is failing though, @glennsarti might be able to have a look at it. Probably because of a file name change.

**Comment by glennsarti** [comment]
> Not sure why the test is failing though,

Nope. The test failure was legit.  Bad JSON file 😃

**Comment by glennsarti** [comment]
Fixed in #51

**Pull request merged**
